### ISSUE TITLE
doesn't compile with rust 1.25

### ISSUE THREAD

**Issue by aep** [drahnr/tokio-mqttc#2]
```
error[E0282]: type annotations needed
   --> /home/aep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-mqttc-0.0.2/src/proto/parsers.rs:145:1
    |
145 | / named_args!(packet_headers(ty: PacketType, fl: PacketFlags) <Headers>, switch!(value!(ty),
146 | |     PacketType::ConnAck => call!(conn_ack_hdrs)                          |
147 | |     PacketType::Publish => call!(publish_hdrs, fl.contains(QOS1 & QOS2)) |
148 | |     PacketType::PubAck => call!(pub_steps_hdrs)                          |
...   |
155 | |     _                    => map!(call!(error, ErrorKind::Custom(2)), |_| Headers::new())
156 | | ));
    | |___^ cannot infer type for `E`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `tokio-mqttc`.

```

**Comment by drahnr** [comment]
This is still mostly WIP and won't even do anything since it has few issues with the connect closure, I am still planning to right this soon-ish and migrate to tokio-0.2.0
